h5Todo/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using h5Todo.Models;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using BC = BCrypt.Net.BCrypt;

namespace h5Todo.Controllers
{
    public class LoginController : Controller
    {
        private readonly IDataProtector _provider;
        private readonly IConfiguration _config;
        private readonly TodoContext _dbContext;

        public LoginController(TodoContext context, IDataProtectionProvider provider, IConfiguration config)
        {
            _dbContext = context;
            _config = config;
            _provider = provider.CreateProtector(_config["secretKey"]);
        }

        public async Task<IActionResult> Login(string password, string username)
        {
            User user = await _dbContext.Users.FirstOrDefaultAsync(u => u.Username == username);

            if (username == null || password == null)
            {
                ViewBag.Message = "Please fill out both fields";
                return View();
            }

            if (user == null)
            {
                ViewBag.Message = "Username or password is incorrect";
                return View();
            }
            else
            {
                try
                {
                    if (BC.Verify(password, user.Password))
                    {
                        HttpContext.Session.SetInt32("UserId", user.UserId);
                        return Redirect("/");
                    }
                    else
                    {
                        ViewBag.Message = "Username or password is incorrect";
                        return View();
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    ViewBag.Message = "Please enter a valid user, or create a new one.";
                    return View();
                }

            }
        }
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<ViewResult> Register(string username, string email, string password)
        {
            var user = await _dbContext.Users.SingleOrDefaultAsync(x => x.Username == username);

            if (user != null)
            {
                ViewBag.Message = "This user already exists";
                return View();
            }

            var createdUser = new User()
            {
                Email = email,
                Password = BC.HashPassword(password),
                Username = username
            };

            await _dbContext.Users.AddAsync(createdUser);
            await _dbContext.SaveChangesAsync();

            ViewBag.Message = "Your new user has been created";
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ChangePasswordPage()
        {
            var model = new User();

            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return Redirect("/login/login");
            }

            User user = await _dbContext.Users.FirstOrDefaultAsync(u => u.UserId == userId);

            model.Username = user.Username;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(string newPassword, string confirmPassword)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return Redirect("/login/login");
            }

            User user = await _dbContext.Users.FirstOrDefaultAsync(u => u.UserId == userId);

            if (user != null && user.UserId == userId)
            {

                if (!string.IsNullOrWhiteSpace(newPassword) && !string.IsNullOrWhiteSpace(confirmPassword))
                {
                    if (newPassword == confirmPassword)
                    {
                        user.Password = BC.HashPassword(confirmPassword);
                    }
                }

                _dbContext.Update(user);
                _dbContext.SaveChanges();
            }

            return Redirect("/");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return Redirect("/");
        }
    }
}

h5Todo/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using h5Todo.Models;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace h5Todo.Controllers
{
    public class TodoController : Controller
    {
        private readonly TodoContext _dbContext;
        private readonly IDataProtector _provider;
        private readonly IConfiguration _config;

        public TodoController(TodoContext context, IDataProtectionProvider provider, IConfiguration config)
        {
            _dbContext = context;
            _config = config;
            _provider = provider.CreateProtector(_config["secretKey"]);
        }

        public async Task<IActionResult> Todo()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return Redirect("/login/login");
            }

            await GetAllTodos(userId);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Todo(string username, string password, Todo todo, string isDone)
        {
            var user = await _dbContext.Users.SingleOrDefaultAsync(x => x.Username == username);
            var userId = HttpContext.Session.GetInt32("UserId");

            if (todo.Title == null)
            {
                ViewBag.Message = "Please provide a title";
                await GetAllTodos(userId);
                return View();
            }

            todo.IsDone = isDone == "true";

            if (todo.Description == null)
            {
                todo.Description = "";
            }

            todo.DateAdded = DateTime.UtcNow;
            if (userId != null) todo.UserId = (int) userId;

            todo.Title = _provider.Protect(todo.Title);
            todo.Description = _provider.Protect(todo.Description);

            _dbContext.Todos.Add(todo);
            _dbContext.SaveChanges();

            return View();
        }

        private async Task GetAllTodos(int? userId)
        {
            ViewBag.todos = await _dbContext.Todos.Where(x => x.UserId == userId.Value).ToListAsync();
            foreach (Todo todo in ViewBag.todos)
            {
                try
                {
                    todo.Title = _provider.Unprotect(todo.Title);
                    todo.Description = _provider.Unprotect(todo.Description);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditTodo([FromQuery]int todoId)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return Redirect("/login/login");
            }

            Todo todo = await _dbContext.Todos.FirstOrDefaultAsync(x => x.TodoId == todoId);

            todo.Title = _provider.Unprotect(todo.Title);
            todo.Description = _provider.Unprotect(todo.Description);

            ViewBag.Todo = todo;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int todoId, string title, string description, string isDone)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return Redirect("/login/login");
            }
            
            Todo todo = await _dbContext.Todos.FirstOrDefaultAsync(x => x.TodoId == todoId);

            if (todo != null && todo.UserId == userId)
            {

                todo.IsDone = isDone == "true";

                if (!string.IsNullOrWhiteSpace(todo.Title))
                {
                    todo.Title = _provider.Protect(title);
                }
                if (!string.IsNullOrWhiteSpace(todo.Description))
                {
                    todo.Description = _provider.Protect(description);
                }

                _dbContext.Update(todo);
                _dbContext.SaveChanges();
            }

            return Redirect("/Todo/todo");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteTodo(int todoId)
        {

            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return Redirect("/login/login");
            }

            Todo todo = await _dbContext.Todos.FirstOrDefaultAsync(x => x.TodoId == todoId);
            if (todo != null && todo.UserId == userId)
            {
                _dbContext.Remove(todo);
                _dbContext.SaveChanges();
            }

            return Redirect("/");
        }

    }
}

h5Todo/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - h5Todo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">h5Todo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Todo">Todos</a>
                        </li>
                        @if (HttpContextAccessor.HttpContext.Session.GetInt32("UserId") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="ChangePasswordPage">Change password</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - h5Todo
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>